media_avportal.settings:
  type: config_object
  label: 'Media AV Portal settings'
  mapping:
    client_api_uri:
      type: uri
      label: 'Client API uri'
      description: 'The API uri endpoint.'
    iframe_base_uri:
      type: uri
      label: 'iFrame base uri'
      description: 'The base URI used in the src attribute of the iframe.'
    photos_base_uri:
      type: uri
      label: 'Photo base uri'
      description: 'The base URI used to in photo resources.'
    cache_max_age:
      type: integer
      label: 'Cache maximum age'

media.source.media_avportal_video:
  type: media.source.field_aware
  label: 'Media AV Portal video source configuration'
  mapping:
    thumbnails_directory:
      type: uri
      label: 'URI of thumbnail storage directory'

media.source.media_avportal_photo:
  type: media.source.field_aware
  label: 'Media AV Portal image source configuration'
  mapping:
    thumbnails_directory:
      type: uri
      label: 'URI of thumbnail storage directory'

field.formatter.settings.avportal_video:
  type: mapping
  label: 'Media AV Portal video display format settings'
  mapping:
    max_width:
      type: integer
      label: 'Maximum width'
    max_height:
      type: integer
      label: 'Maximum height'

field.formatter.settings.avportal_photo:
  type: mapping
  label: 'Media AV Portal photo display format settings'
  mapping:
    image_style:
      type: string
      label: 'Image style'

field.formatter.settings.avportal_photo_responsive:
  type: mapping
  label: 'Responsive image format settings'
  mapping:
    responsive_image_style:
      type: string
      label: 'Responsive image style'


field.widget.settings.avportal_textfield:
  type: field.widget.settings.string_textfield
